name: background_task_optimizer
description: "A Flutter package to optimize background task management using isolates and concurrency."
version: 1.1.3
homepage: https://github.com/RuLevyDev/background_task_optimizer

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


keywords:
  - flutter
  - dart
  - isolates
  - background task
  - concurrency

repository: https://github.com/RuLevyDev/background_task_optimizer.git
issue_tracker: https://github.com/RuLevyDev/background_task_optimizer/issues

license: MIT
