name: CI/CD for Flutter Package

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  test_analyze:
    name: Test & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Usa la versión que prefieras

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  # Publicación desactivada en esta etapa
  publish:
    name: Publish to Pub.dev (DISABLED)
    needs: test_analyze
    if: false  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Install Dependencies
        run: flutter pub get

      - name: Validate Publish
        run: dart pub publish --dry-run

      - name: Publish to Pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json && dart pub publish -f
